In [14]:
import pandas as pd

In [15]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "car_prices.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "syedanwarafridi/vehicle-sales-data",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())
print(df.info())
print(df.head(5))

/tmp/ipykernel_218/24882898.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Using Colab cache for faster access to the 'vehicle-sales-data' dataset.
First 5 records:    year   make                model        trim   body transmission  \
0  2015    Kia              Sorento          LX    SUV    automatic
1  2015    Kia              Sorento          LX    SUV    automatic
2  2014    BMW             3 Series  328i SULEV  Sedan    automatic
3  2015  Volvo                  S60          T5  Sedan    automatic
4  2014    BMW  6 Series Gran Coupe        650i  Sedan    automatic

                 vin state  condition  odometer  color interior  \
0  5xyktca69fg566472    ca        5.0   16639.0  white    black
1  5xyktca69fg561319    ca        5.0    9393.0  white    beige
2  wba3c1c51ek116351    ca       45.0    1331.0   gray    black
3  yv1612tb4f1310987    ca       41.0   14282.0  white    black
4  wba6b2c57ed129731    ca       43.0    2641.0   gray    black

                                   seller      mmr  sellingprice  \
0                 kia motors america  inc  20500.0       21500.0
1                 kia motors america  inc  20800.0       21500.0
2  financial services remarketing (lease)  31900.0       30000.0
3                 volvo na rep/world omni  27500.0       27750.0
4  financial services remarketing (lease)  66000.0       67000.0

                                  saledate
0  Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
1  Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
2  Thu Jan 15 2015 04:30:00 GMT-0800 (PST)
3  Thu Jan 29 2015 04:30:00 GMT-0800 (PST)
4  Thu Dec 18 2014 12:30:00 GMT-0800 (PST)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 558837 entries, 0 to 558836
Data columns (total 16 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   year          558837 non-null  int64
 1   make          548536 non-null  object
 2   model         548438 non-null  object
 3   trim          548186 non-null  object
 4   body          545642 non-null  object
 5   transmission  493485 non-null  object
 6   vin           558833 non-null  object
 7   state         558837 non-null  object
 8   condition     547017 non-null  float64
 9   odometer      558743 non-null  float64
 10  color         558088 non-null  object
 11  interior      558088 non-null  object
 12  seller        558837 non-null  object
 13  mmr           558799 non-null  float64
 14  sellingprice  558825 non-null  float64
 15  saledate      558825 non-null  object
dtypes: float64(4), int64(1), object(11)
memory usage: 68.2+ MB
None
   year   make                model        trim   body transmission  \
0  2015    Kia              Sorento          LX    SUV    automatic
1  2015    Kia              Sorento          LX    SUV    automatic
2  2014    BMW             3 Series  328i SULEV  Sedan    automatic
3  2015  Volvo                  S60          T5  Sedan    automatic
4  2014    BMW  6 Series Gran Coupe        650i  Sedan    automatic

                 vin state  condition  odometer  color interior  \
0  5xyktca69fg566472    ca        5.0   16639.0  white    black
1  5xyktca69fg561319    ca        5.0    9393.0  white    beige
2  wba3c1c51ek116351    ca       45.0    1331.0   gray    black
3  yv1612tb4f1310987    ca       41.0   14282.0  white    black
4  wba6b2c57ed129731    ca       43.0    2641.0   gray    black

                                   seller      mmr  sellingprice  \
0                 kia motors america  inc  20500.0       21500.0
1                 kia motors america  inc  20800.0       21500.0
2  financial services remarketing (lease)  31900.0       30000.0
3                 volvo na rep/world omni  27500.0       27750.0
4  financial services remarketing (lease)  66000.0       67000.0

                                  saledate
0  Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
1  Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
2  Thu Jan 15 2015 04:30:00 GMT-0800 (PST)
3  Thu Jan 29 2015 04:30:00 GMT-0800 (PST)
4  Thu Dec 18 2014 12:30:00 GMT-0800 (PST)

In [16]:
#df = df.drop(['mmr', 'vin', 'saledate'], axis=1, errors='ignore')
df = df.dropna(subset=['sellingprice'])
num_cols = df.select_dtypes(include=['float64', 'int64']).columns.drop('sellingprice')
for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

cat_cols = df.select_dtypes(include=['object']).columns
for col in cat_cols:
    df[col] = df[col].fillna('Unknown')
    df[col] = df[col].astype(str)

df['model_new'] = df['make']+' '+df['model']
df['model_new2'] = df['make'] + ' '

print(df.info())
print(df.head(5))

<class 'pandas.core.frame.DataFrame'>
Index: 558825 entries, 0 to 558836
Data columns (total 18 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   year          558825 non-null  int64
 1   make          558825 non-null  object
 2   model         558825 non-null  object
 3   trim          558825 non-null  object
 4   body          558825 non-null  object
 5   transmission  558825 non-null  object
 6   vin           558825 non-null  object
 7   state         558825 non-null  object
 8   condition     558825 non-null  float64
 9   odometer      558825 non-null  float64
 10  color         558825 non-null  object
 11  interior      558825 non-null  object
 12  seller        558825 non-null  object
 13  mmr           558825 non-null  float64
 14  sellingprice  558825 non-null  float64
 15  saledate      558825 non-null  object
 16  model_new     558825 non-null  object
 17  model_new2    558825 non-null  object
dtypes: float64(4), int64(1), object(13)
memory usage: 81.0+ MB
None
   year   make                model        trim   body transmission  \
0  2015    Kia              Sorento          LX    SUV    automatic
1  2015    Kia              Sorento          LX    SUV    automatic
2  2014    BMW             3 Series  328i SULEV  Sedan    automatic
3  2015  Volvo                  S60          T5  Sedan    automatic
4  2014    BMW  6 Series Gran Coupe        650i  Sedan    automatic

                 vin state  condition  odometer  color interior  \
0  5xyktca69fg566472    ca        5.0   16639.0  white    black
1  5xyktca69fg561319    ca        5.0    9393.0  white    beige
2  wba3c1c51ek116351    ca       45.0    1331.0   gray    black
3  yv1612tb4f1310987    ca       41.0   14282.0  white    black
4  wba6b2c57ed129731    ca       43.0    2641.0   gray    black

                                   seller      mmr  sellingprice  \
0                 kia motors america  inc  20500.0       21500.0
1                 kia motors america  inc  20800.0       21500.0
2  financial services remarketing (lease)  31900.0       30000.0
3                 volvo na rep/world omni  27500.0       27750.0
4  financial services remarketing (lease)  66000.0       67000.0

                                  saledate                model_new model_new2
0  Tue Dec 16 2014 12:30:00 GMT-0800 (PST)              Kia Sorento       Kia
1  Tue Dec 16 2014 12:30:00 GMT-0800 (PST)              Kia Sorento       Kia
2  Thu Jan 15 2015 04:30:00 GMT-0800 (PST)             BMW 3 Series       BMW
3  Thu Jan 29 2015 04:30:00 GMT-0800 (PST)                Volvo S60     Volvo
4  Thu Dec 18 2014 12:30:00 GMT-0800 (PST)  BMW 6 Series Gran Coupe       BMW

In [17]:
dataset_path = kagglehub.dataset_download("CooperUnion/cardataset")

df2 = pd.read_csv(f"{dataset_path}/data.csv")

df2.head()

Using Colab cache for faster access to the 'cardataset' dataset.

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

In [18]:
for col in ['make', 'model']:
    df[col] = df[col].str.lower().str.strip()

for col in ['Make', 'Model']:
    df2[col] = df2[col].str.lower().str.strip()

df['model_new'] = df['make']+' '+df['model']
df['model_new2'] = df['make'] + ' '
df2['model_new'] = df2['Make']+' '+df2['Model']

print(df.head(5))
print(df2.head(5))

   year   make                model        trim   body transmission  \
0  2015    kia              sorento          LX    SUV    automatic
1  2015    kia              sorento          LX    SUV    automatic
2  2014    bmw             3 series  328i SULEV  Sedan    automatic
3  2015  volvo                  s60          T5  Sedan    automatic
4  2014    bmw  6 series gran coupe        650i  Sedan    automatic

                 vin state  condition  odometer  color interior  \
0  5xyktca69fg566472    ca        5.0   16639.0  white    black
1  5xyktca69fg561319    ca        5.0    9393.0  white    beige
2  wba3c1c51ek116351    ca       45.0    1331.0   gray    black
3  yv1612tb4f1310987    ca       41.0   14282.0  white    black
4  wba6b2c57ed129731    ca       43.0    2641.0   gray    black

                                   seller      mmr  sellingprice  \
0                 kia motors america  inc  20500.0       21500.0
1                 kia motors america  inc  20800.0       21500.0
2  financial services remarketing (lease)  31900.0       30000.0
3                 volvo na rep/world omni  27500.0       27750.0
4  financial services remarketing (lease)  66000.0       67000.0

                                  saledate                model_new model_new2
0  Tue Dec 16 2014 12:30:00 GMT-0800 (PST)              kia sorento       kia
1  Tue Dec 16 2014 12:30:00 GMT-0800 (PST)              kia sorento       kia
2  Thu Jan 15 2015 04:30:00 GMT-0800 (PST)             bmw 3 series       bmw
3  Thu Jan 29 2015 04:30:00 GMT-0800 (PST)                volvo s60     volvo
4  Thu Dec 18 2014 12:30:00 GMT-0800 (PST)  bmw 6 series gran coupe       bmw
  Make       Model  Year             Engine Fuel Type  Engine HP  \
0  bmw  1 series m  2011  premium unleaded (required)      335.0
1  bmw    1 series  2011  premium unleaded (required)      300.0
2  bmw    1 series  2011  premium unleaded (required)      300.0
3  bmw    1 series  2011  premium unleaded (required)      230.0
4  bmw    1 series  2011  premium unleaded (required)      230.0

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0
1               6.0            MANUAL  rear wheel drive              2.0
2               6.0            MANUAL  rear wheel drive              2.0
3               6.0            MANUAL  rear wheel drive              2.0
4               6.0            MANUAL  rear wheel drive              2.0

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe
1                     Luxury,Performance      Compact   Convertible
2                Luxury,High-Performance      Compact         Coupe
3                     Luxury,Performance      Compact         Coupe
4                                 Luxury      Compact   Convertible

   highway MPG  city mpg  Popularity   MSRP       model_new
0           26        19        3916  46135  bmw 1 series m
1           28        19        3916  40650    bmw 1 series
2           28        20        3916  36350    bmw 1 series
3           28        18        3916  29450    bmw 1 series
4           28        18        3916  34500    bmw 1 series

In [19]:
df2['Market Category'] = df2['Market Category'].fillna('')

df2['Market Category'] = df2['Market Category'].str.replace(', ', ',')
df2['Market Category'] = df2['Market Category'].str.replace(' ,', ',')

market_categories_encoded = df2['Market Category'].str.get_dummies(sep=',')


market_categories_encoded = market_categories_encoded.add_prefix('MarketCat_')
import pandas as pd

df2 = pd.concat([df2, market_categories_encoded], axis=1)

df2 = df2.drop('Market Category', axis=1)
print(df2.head())

  Make       Model  Year             Engine Fuel Type  Engine HP  \
0  bmw  1 series m  2011  premium unleaded (required)      335.0
1  bmw    1 series  2011  premium unleaded (required)      300.0
2  bmw    1 series  2011  premium unleaded (required)      300.0
3  bmw    1 series  2011  premium unleaded (required)      230.0
4  bmw    1 series  2011  premium unleaded (required)      230.0

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0
1               6.0            MANUAL  rear wheel drive              2.0
2               6.0            MANUAL  rear wheel drive              2.0
3               6.0            MANUAL  rear wheel drive              2.0
4               6.0            MANUAL  rear wheel drive              2.0

  Vehicle Size  ... MarketCat_Crossover  MarketCat_Diesel  MarketCat_Exotic  \
0      Compact  ...                   0                 0                 0
1      Compact  ...                   0                 0                 0
2      Compact  ...                   0                 0                 0
3      Compact  ...                   0                 0                 0
4      Compact  ...                   0                 0                 0

   MarketCat_Factory Tuner  MarketCat_Flex Fuel MarketCat_Hatchback  \
0                        1                    0                   0
1                        0                    0                   0
2                        0                    0                   0
3                        0                    0                   0
4                        0                    0                   0

   MarketCat_High-Performance  MarketCat_Hybrid  MarketCat_Luxury  \
0                           1                 0                 1
1                           0                 0                 1
2                           1                 0                 1
3                           0                 0                 1
4                           0                 0                 1

   MarketCat_Performance
0                      0
1                      1
2                      0
3                      1
4                      0

[5 rows x 26 columns]

In [20]:

cat_cols = [
    'Engine Fuel Type', 'Transmission Type',
    'Driven_Wheels', 'Vehicle Size', 'Vehicle Style'
]

df2_encoded = pd.get_dummies(df2, columns=cat_cols, dummy_na=False, dtype=int)

group_cols = ['model_new', 'Year', 'Make', 'Model']

df2_aggregated = df2_encoded.groupby(group_cols).mean().reset_index()

df2_aggregated.head()

,model_new,Year,Make,Model,Engine HP,Engine Cylinders,Number of Doors,highway MPG,city mpg,Popularity,...,Vehicle Style_Convertible,Vehicle Style_Convertible SUV,Vehicle Style_Coupe,Vehicle Style_Crew Cab Pickup,Vehicle Style_Extended Cab Pickup,Vehicle Style_Passenger Minivan,Vehicle Style_Passenger Van,Vehicle Style_Regular Cab Pickup,Vehicle Style_Sedan,Vehicle Style_Wagon
0,acura cl,2001,acura,cl,225.00,6.0,2.0,27.0,17.0,204.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,acura cl,2002,acura,cl,225.00,6.0,2.0,27.0,17.0,204.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,acura cl,2003,acura,cl,246.00,6.0,2.0,26.6,17.0,204.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,acura ilx,2015,acura,ilx,162.75,4.0,4.0,34.0,23.5,204.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,acura ilx,2016,acura,ilx,201.00,4.0,4.0,36.0,25.0,204.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [21]:
df['year'] = df['year'].fillna(0).astype(int)
df2_aggregated['Year'] = df2_aggregated['Year'].astype(int)

df = df.sort_values('year')
df2_aggregated = df2_aggregated.sort_values('Year')

merged_df = pd.merge_asof(
    left=df,
    right=df2_aggregated,
    left_on='year',
    right_on='Year',
    left_by=['make', 'model'],
    right_by=['Make', 'Model'],
    direction='backward'
)

columns_to_drop = ['Year', 'Make', 'Model', 'model_new']
merged_df = merged_df.drop(columns=columns_to_drop, errors='ignore')

merged_df = merged_df.sort_index()

merged_df['saledate_parsed'] = pd.to_datetime(merged_df['saledate'], utc=True, errors='coerce')

merged_df['sale_year'] = merged_df['saledate_parsed'].dt.year

merged_df['car_age'] = merged_df['sale_year'] - merged_df['year']

merged_df['car_age'] = merged_df['car_age'].clip(lower=0)

merged_df = merged_df.drop(columns=['saledate', 'saledate_parsed', 'sale_year'])

print(merged_df[['year', 'car_age']].head())

merged_df.head()
merged_df.info()

/tmp/ipykernel_218/2714956529.py:22: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  merged_df['saledate_parsed'] = pd.to_datetime(merged_df['saledate'], utc=True, errors='coerce')

   year  car_age
0  1982     33.0
1  1982     33.0
2  1983     32.0
3  1984     31.0
4  1984     31.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 558825 entries, 0 to 558824
Data columns (total 74 columns):
 #   Column                                                         Non-Null Count   Dtype
---  ------                                                         --------------   -----
 0   year                                                           558825 non-null  int64
 1   make                                                           558825 non-null  object
 2   model                                                          558825 non-null  object
 3   trim                                                           558825 non-null  object
 4   body                                                           558825 non-null  object
 5   transmission                                                   558825 non-null  object
 6   vin                                                            558825 non-null  object
 7   state                                                          558825 non-null  object
 8   condition                                                      558825 non-null  float64
 9   odometer                                                       558825 non-null  float64
 10  color                                                          558825 non-null  object
 11  interior                                                       558825 non-null  object
 12  seller                                                         558825 non-null  object
 13  mmr                                                            558825 non-null  float64
 14  sellingprice                                                   558825 non-null  float64
 15  model_new_x                                                    558825 non-null  object
 16  model_new2                                                     558825 non-null  object
 17  model_new_y                                                    67228 non-null   object
 18  Engine HP                                                      67125 non-null   float64
 19  Engine Cylinders                                               67213 non-null   float64
 20  Number of Doors                                                67228 non-null   float64
 21  highway MPG                                                    67228 non-null   float64
 22  city mpg                                                       67228 non-null   float64
 23  Popularity                                                     67228 non-null   float64
 24  MSRP                                                           67228 non-null   float64
 25  MarketCat_Crossover                                            67228 non-null   float64
 26  MarketCat_Diesel                                               67228 non-null   float64
 27  MarketCat_Exotic                                               67228 non-null   float64
 28  MarketCat_Factory Tuner                                        67228 non-null   float64
 29  MarketCat_Flex Fuel                                            67228 non-null   float64
 30  MarketCat_Hatchback                                            67228 non-null   float64
 31  MarketCat_High-Performance                                     67228 non-null   float64
 32  MarketCat_Hybrid                                               67228 non-null   float64
 33  MarketCat_Luxury                                               67228 non-null   float64
 34  MarketCat_Performance                                          67228 non-null   float64
 35  Engine Fuel Type_diesel                                        67228 non-null   float64
 36  Engine Fuel Type_electric                                      67228 non-null   float64
 37  Engine Fuel Type_flex-fuel (premium unleaded recommended/E85)  67228 non-null   float64
 38  Engine Fuel Type_flex-fuel (premium unleaded required/E85)     67228 non-null   float64
 39  Engine Fuel Type_flex-fuel (unleaded/E85)                      67228 non-null   float64
 40  Engine Fuel Type_flex-fuel (unleaded/natural gas)              67228 non-null   float64
 41  Engine Fuel Type_natural gas                                   67228 non-null   float64
 42  Engine Fuel Type_premium unleaded (recommended)                67228 non-null   float64
 43  Engine Fuel Type_premium unleaded (required)                   67228 non-null   float64
 44  Engine Fuel Type_regular unleaded                              67228 non-null   float64
 45  Transmission Type_AUTOMATED_MANUAL                             67228 non-null   float64
 46  Transmission Type_AUTOMATIC                                    67228 non-null   float64
 47  Transmission Type_DIRECT_DRIVE                                 67228 non-null   float64
 48  Transmission Type_MANUAL                                       67228 non-null   float64
 49  Transmission Type_UNKNOWN                                      67228 non-null   float64
 50  Driven_Wheels_all wheel drive                                  67228 non-null   float64
 51  Driven_Wheels_four wheel drive                                 67228 non-null   float64
 52  Driven_Wheels_front wheel drive                                67228 non-null   float64
 53  Driven_Wheels_rear wheel drive                                 67228 non-null   float64
 54  Vehicle Size_Compact                                           67228 non-null   float64
 55  Vehicle Size_Large                                             67228 non-null   float64
 56  Vehicle Size_Midsize                                           67228 non-null   float64
 57  Vehicle Style_2dr Hatchback                                    67228 non-null   float64
 58  Vehicle Style_2dr SUV                                          67228 non-null   float64
 59  Vehicle Style_4dr Hatchback                                    67228 non-null   float64
 60  Vehicle Style_4dr SUV                                          67228 non-null   float64
 61  Vehicle Style_Cargo Minivan                                    67228 non-null   float64
 62  Vehicle Style_Cargo Van                                        67228 non-null   float64
 63  Vehicle Style_Convertible                                      67228 non-null   float64
 64  Vehicle Style_Convertible SUV                                  67228 non-null   float64
 65  Vehicle Style_Coupe                                            67228 non-null   float64
 66  Vehicle Style_Crew Cab Pickup                                  67228 non-null   float64
 67  Vehicle Style_Extended Cab Pickup                              67228 non-null   float64
 68  Vehicle Style_Passenger Minivan                                67228 non-null   float64
 69  Vehicle Style_Passenger Van                                    67228 non-null   float64
 70  Vehicle Style_Regular Cab Pickup                               67228 non-null   float64
 71  Vehicle Style_Sedan                                            67228 non-null   float64
 72  Vehicle Style_Wagon                                            67228 non-null   float64
 73  car_age                                                        558799 non-null  float64
dtypes: float64(60), int64(1), object(13)
memory usage: 315.5+ MB

In [22]:
pip install catboost

Requirement already satisfied: catboost in /usr/local/lib/python3.12/dist-packages (1.2.10)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)

In [23]:
from sklearn.model_selection import train_test_split
from catboost import CatBoostRegressor

merged_df = merged_df.dropna(subset=['Engine HP'])

cols_to_drop = ['sellingprice', 'mmr', 'vin']
X = merged_df.drop(columns=[col for col in cols_to_drop if col in merged_df.columns])
y = merged_df['sellingprice']

cat_features = X.select_dtypes(include=['object', 'category']).columns.tolist()

for col in cat_features:
    X[col] = X[col].fillna('missing').astype(str)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training on {len(X_train)} perfectly matched cars!")

Training on 53700 perfectly matched cars!

In [24]:
model = CatBoostRegressor(
    iterations=1000,
    learning_rate=0.1,
    depth=8,
    loss_function='RMSE',
    verbose=100,
    task_type='CPU',
    cat_features=cat_features
)


model.fit(
    X_train,
    y_train,
    eval_set=(X_test, y_test),
    early_stopping_rounds=50
)

0:	learn: 10464.1575778	test: 10431.5202903	best: 10431.5202903 (0)	total: 744ms	remaining: 12m 23s
100:	learn: 2101.7320784	test: 2109.5765711	best: 2109.5765711 (100)	total: 46.5s	remaining: 6m 53s
200:	learn: 1839.3818983	test: 1936.8670207	best: 1936.8670207 (200)	total: 1m 19s	remaining: 5m 14s
300:	learn: 1704.0994052	test: 1870.2249579	best: 1870.2249579 (300)	total: 1m 50s	remaining: 4m 16s
400:	learn: 1606.0599412	test: 1832.8958789	best: 1832.8958789 (400)	total: 2m 25s	remaining: 3m 37s
500:	learn: 1533.5518102	test: 1808.1931624	best: 1808.1931624 (500)	total: 2m 56s	remaining: 2m 55s
600:	learn: 1474.6101511	test: 1791.6991083	best: 1791.6991083 (600)	total: 3m 28s	remaining: 2m 18s
700:	learn: 1423.4145573	test: 1780.5287534	best: 1780.5287534 (700)	total: 4m 7s	remaining: 1m 45s
800:	learn: 1379.7777695	test: 1774.2928226	best: 1774.2928226 (800)	total: 4m 38s	remaining: 1m 9s
900:	learn: 1344.7187895	test: 1768.7028323	best: 1768.5710859 (899)	total: 5m 15s	remaining: 34.7s
999:	learn: 1312.7171983	test: 1764.9997667	best: 1764.9997667 (999)	total: 5m 46s	remaining: 0us

bestTest = 1764.999767
bestIteration = 999

CatBoostRegressor(cat_features=['make', 'model', 'trim', 'body', 'transmission', 'state', 'color', 'interior', 'seller', 'model_new_x', 'model_new2', 'model_new_y'], depth=8, iterations=1000, learning_rate=0.1, loss_function='RMSE', task_type='CPU', verbose=100)

In [25]:
from sklearn.metrics import mean_absolute_error

predictions = model.predict(X_test)
mae = mean_absolute_error(y_test, predictions)
print(mae)

1038.1870153761827

In [26]:
merged_df.to_csv("output2.csv")